# Generated by Django 3.2.25 on 2024-09-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=128, verbose_name='Event title')),
                ('description', models.CharField(max_length=512, verbose_name='Event description')),
                ('location', models.JSONField(verbose_name='Event coordinates')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
