# Generated by Django 3.2.25 on 2024-09-07 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('additionalinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.additionalinfo')),
                ('title', models.CharField(max_length=128, verbose_name='Event title')),
                ('description', models.CharField(max_length=512, verbose_name='Event description')),
                ('location', models.JSONField(verbose_name='Event coordinates')),
            ],
            bases=('events.additionalinfo',),
        ),
    ]
